require('colors');
const fs = require('fs');
const path = require('path');
const { Words } = require('./words');
const timeKey = 'wordle-time'.green;
console.time(timeKey);
const words = new Words();
const pattern = fs.readFileSync(path.join(__dirname, '../input/pattern.txt'), 'utf8').split('\n')[0];
const excludePatterns = fs.readFileSync(path.join(__dirname, '../input/exclude-patterns.txt'), 'utf8').split('\n');
const includeLetters = fs.readFileSync(path.join(__dirname, '../input/include-letters.txt'), 'utf8').split('\n')[0].split('');
const ignoreLetters = fs.readFileSync(path.join(__dirname, '../input/ignore-letters.txt'), 'utf8').split('\n')[0].split('');
const wordsDict = words.match(pattern, excludePatterns.filter(p=>!!p), includeLetters, ignoreLetters).map(word => ({ word }));
console.table(wordsDict);
console.log(`Found ${wordsDict.length} words.`.bgYellow.black);
console.timeEnd(timeKey);
